version: '3'

services:
  smart-message-mock-service:
    build: .
    container_name: smart-message-mock-service
    ports:
      - '13000:3000'
    image: smart-message-mock-service:0.0.1-snapshot
    networks:
      - smart-msg
    

networks:
  smart-msg:
    external: true